---
title: "p8105_hw6_jl6321.Rmd"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2

Read in and manipulate the data: 
```{r}
homicide = read_csv("./data/homicide-data.csv") %>% 
  unite(col = "city_state", city:state, sep = ", ", remove = FALSE) %>% 
  mutate(ifsolved = ifelse(disposition == "Closed by arrest", 1, 0), 
         victim_age = as.numeric(victim_age)) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>% 
  filter(victim_race %in% c("White", "Black")) 
```

Fit a logistic regression model for Baltimore: 
```{r}
baltimore = 
  homicide %>% 
  filter(city_state == "Baltimore, MD") 

baltimore_model = 
  baltimore %>% 
  glm(ifsolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

baltimore_model %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), 
         lower_bound = exp(estimate - std.error * 1.96), 
         upper_bound = exp(estimate + std.error * 1.96)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(term, log_OR = estimate, OR, lower_bound, upper_bound, p.value) %>% 
  rename("odds_ratio" = OR, "log_odds_ratio" = log_OR) %>% 
  knitr::kable(digits = 3)
```
Keeping all other variables fixed, the estimate of odds ratio for solving homicides comparing male victims to female victims is 0.426 with a 95% confidence interval from 0.325 to 0.558, indicating that solved male-victim homicide cases is 0.426 as solved female victim cases. 

```{r}
all_cities = 
  homicide %>% 
  group_by(city_state) %>% 
  nest() 

all_cities %>% 
  mutate(models = map(data, ~glm(ifsolved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())), 
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(OR = exp(estimate), 
         lower_bound = exp(estimate - std.error * 1.96), 
         upper_bound = exp(estimate + std.error * 1.96)) %>% 
  select(city_state, term, OR, lower_bound, upper_bound) %>% 
  mutate(city_state = fct_reorder(city_state, OR)) 
```

