p8105_hw6_jl6321.Rmd
================

## Problem 2

Read in and manipulate the data:

``` r
homicide = read_csv("./data/homicide-data.csv") %>% 
  unite(col = "city_state", city:state, sep = ", ", remove = FALSE) %>% 
  mutate(ifsolved = ifelse(disposition == "Closed by arrest", 1, 0), 
         victim_age = as.numeric(victim_age)) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>% 
  filter(victim_race %in% c("White", "Black")) 
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion

Fit a logistic regression model for Baltimore:

``` r
baltimore = 
  homicide %>% 
  filter(city_state == "Baltimore, MD") 

baltimore_model = 
  baltimore %>% 
  glm(ifsolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

baltimore_model %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), 
         lower_bound = exp(estimate - std.error * 1.96), 
         upper_bound = exp(estimate + std.error * 1.96)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(term, log_OR = estimate, OR, lower_bound, upper_bound, p.value) %>% 
  rename("odds_ratio" = OR, "log_odds_ratio" = log_OR) %>% 
  knitr::kable(digits = 3)
```

| term           | log_odds_ratio | odds_ratio | lower_bound | upper_bound | p.value |
|:---------------|---------------:|-----------:|------------:|------------:|--------:|
| victim_sexMale |         -0.854 |      0.426 |       0.325 |       0.558 |       0 |

Keeping all other variables fixed, the estimate of odds ratio for
solving homicides comparing male victims to female victims is 0.426 with
a 95% confidence interval from 0.325 to 0.558, indicating that solved
male-victim homicide cases is 0.426 as solved female victim cases.

``` r
all_cities = 
  homicide %>% 
  group_by(city_state) %>% 
  nest() 

all_cities %>% 
  mutate(models = map(data, ~glm(ifsolved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())), 
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(OR = exp(estimate), 
         lower_bound = exp(estimate - std.error * 1.96), 
         upper_bound = exp(estimate + std.error * 1.96)) %>% 
  select(city_state, term, OR, lower_bound, upper_bound) %>% 
  mutate(city_state = fct_reorder(city_state, OR)) 
```

    ## Warning: `cols` is now required when using unnest().
    ## Please use `cols = c(models)`

    ## # A tibble: 47 × 5
    ## # Groups:   city_state [47]
    ##    city_state      term              OR lower_bound upper_bound
    ##    <fct>           <chr>          <dbl>       <dbl>       <dbl>
    ##  1 Albuquerque, NM victim_sexMale 1.77        0.831       3.76 
    ##  2 Atlanta, GA     victim_sexMale 1.00        0.684       1.46 
    ##  3 Baltimore, MD   victim_sexMale 0.426       0.325       0.558
    ##  4 Baton Rouge, LA victim_sexMale 0.381       0.209       0.695
    ##  5 Birmingham, AL  victim_sexMale 0.870       0.574       1.32 
    ##  6 Boston, MA      victim_sexMale 0.674       0.356       1.28 
    ##  7 Buffalo, NY     victim_sexMale 0.521       0.290       0.935
    ##  8 Charlotte, NC   victim_sexMale 0.884       0.557       1.40 
    ##  9 Chicago, IL     victim_sexMale 0.410       0.336       0.501
    ## 10 Cincinnati, OH  victim_sexMale 0.400       0.236       0.677
    ## # … with 37 more rows
